.

diff --git a/.github/workflows/build-and-test-x86.yml b/.github/workflows/build-and-test-x86.yml
--- a/.github/workflows/build-and-test-x86.yml
+++ b/.github/workflows/build-and-test-x86.yml
@@ -50,8 +50,7 @@ jobs:
           overwrite: true
           retention-days: 1
       - if: ${{ steps.bat.outputs.success == 'false' }}
-        uses: actions/github-script@v7
-        with:
-          script: |
-            echo "${{ steps.bat.outputs.msg }}"
-            core.setFailed("Generation for Intel x86 failed")
+        run: |
+          echo "Build and testing for Intel x86 failed"
+          echo "${{ steps.bat.outputs.msg }}"
+          exit 1
diff --git a/.github/workflows/validate-tsl.yml b/.github/workflows/validate-tsl.yml
--- a/.github/workflows/validate-tsl.yml
+++ b/.github/workflows/validate-tsl.yml
@@ -40,9 +40,8 @@ jobs:
           overwrite: true
           retention-days: 1
       - if: ${{ steps.validate.outputs.success == 'false' }}
-        uses: actions/github-script@v7
-        with:
-          script: |
-            echo "${{ steps.validate.outputs.msg }}"
-            core.setFailed("Validation failed.")
+        run: |
+          echo "Validation failed"
+          echo "${{ steps.validate.outputs.msg }}"
+          exit 1
 
