.

diff --git a/.github/workflows/generate-tsl.yml b/.github/workflows/generate-tsl.yml
--- a/.github/workflows/generate-tsl.yml
+++ b/.github/workflows/generate-tsl.yml
@@ -8,70 +8,70 @@ on:
       - completed
 
 jobs:
-  generate-for-intel:
-    runs-on: ubuntu-latest
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
-    name: Job to generate TSL for Intel x86
-    strategy:
-      matrix:
-        target_flags:
-          - "sse,sse2"
-          - "sse,sse2,ssse3"
-          - "sse,sse2,ssse3,sse4_1"
-          - "sse,sse2,ssse3,sse4_1,sse4_2"
-          - "sse,sse2,ssse3,sse4_1,sse4_2,avx"
-          - "sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2"
-          - "sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2,avx512f"
-          - "sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2,avx512f,avx512cd,avx512er,avx512pf" #avx3.1
-          - "sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2,avx512f,avx512cd,avx512bw,avx512dq,avx512vl" #avx3.2
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: TSL Generate
-        id: generate
-        uses: ./.github/actions/tsl-generate
-        with:
-          image: ${{ vars.GENERATION_TAG }}
-          targets: ${{ matrix.target_flags }}
-      - name: TSL Generate Output
-        if: always()
-        run: echo "TSL Generation ${{ steps.generate.outputs.msg }}"
-      - if: ${{ steps.generate.outputs.success == 'false' }}
-        run: "echo SUCCESS == false"
-      - if: ${{ steps.generate.outputs.success == 'true' }}
-        run: "echo SUCCESS == true"
-      - name: Upload Generated TSL
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: generate_tsl_intel_${{ steps.generate.outputs.name }}
-          path: ${{ github.workspace }}/${{ steps.generate.outputs.out }}
-          overwrite: true
-          retention-days: 1
-      - if: ${{ steps.generate.outputs.success == 'false' }}
-        run: |
-          echo "Generation for Intel x86 failed"
-          echo "${{ steps.generate.outputs.msg }}"
-          exit 1
-  package-for-intel:
-    runs-on: ubuntu-latest
-    name: Job to package TSL for Intel x86
-    needs: generate-for-intel
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Download Generated TSL
-        uses: actions/download-artifact@v4
-        with:
-          pattern: generate_tsl_intel_*
-          path: ${{ github.workspace }}/tsl_intel
-      - name: Upload Packaged TSL
-        uses: actions/upload-artifact@v4
-        with:
-          name: TSL_INTEL
-          path: ${{ github.workspace }}/tsl_intel
-          overwrite: true
-          retention-days: 1
+  # generate-for-intel:
+  #   runs-on: ubuntu-latest
+  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
+  #   name: Job to generate TSL for Intel x86
+  #   strategy:
+  #     matrix:
+  #       target_flags:
+  #         - "sse,sse2"
+  #         - "sse,sse2,ssse3"
+  #         - "sse,sse2,ssse3,sse4_1"
+  #         - "sse,sse2,ssse3,sse4_1,sse4_2"
+  #         - "sse,sse2,ssse3,sse4_1,sse4_2,avx"
+  #         - "sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2"
+  #         - "sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2,avx512f"
+  #         - "sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2,avx512f,avx512cd,avx512er,avx512pf" #avx3.1
+  #         - "sse,sse2,ssse3,sse4_1,sse4_2,avx,avx2,avx512f,avx512cd,avx512bw,avx512dq,avx512vl" #avx3.2
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: TSL Generate
+  #       id: generate
+  #       uses: ./.github/actions/tsl-generate
+  #       with:
+  #         image: ${{ vars.GENERATION_TAG }}
+  #         targets: ${{ matrix.target_flags }}
+  #     - name: TSL Generate Output
+  #       if: always()
+  #       run: echo "TSL Generation ${{ steps.generate.outputs.msg }}"
+  #     - if: ${{ steps.generate.outputs.success == 'false' }}
+  #       run: "echo SUCCESS == false"
+  #     - if: ${{ steps.generate.outputs.success == 'true' }}
+  #       run: "echo SUCCESS == true"
+  #     - name: Upload Generated TSL
+  #       if: always()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: generate_tsl_intel_${{ steps.generate.outputs.name }}
+  #         path: ${{ github.workspace }}/${{ steps.generate.outputs.out }}
+  #         overwrite: true
+  #         retention-days: 1
+  #     - if: ${{ steps.generate.outputs.success == 'false' }}
+  #       run: |
+  #         echo "Generation for Intel x86 failed"
+  #         echo "${{ steps.generate.outputs.msg }}"
+  #         exit 1
+  # package-for-intel:
+  #   runs-on: ubuntu-latest
+  #   name: Job to package TSL for Intel x86
+  #   needs: generate-for-intel
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Download Generated TSL
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         pattern: generate_tsl_intel_*
+  #         path: ${{ github.workspace }}/tsl_intel
+  #     - name: Upload Packaged TSL
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: TSL_INTEL
+  #         path: ${{ github.workspace }}/tsl_intel
+  #         overwrite: true
+  #         retention-days: 1
   generate-for-arm:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
