.

diff --git a/.github/workflows/generate-tsl.yml b/.github/workflows/generate-tsl.yml
--- a/.github/workflows/generate-tsl.yml
+++ b/.github/workflows/generate-tsl.yml
@@ -15,7 +15,6 @@ jobs:
     strategy:
       matrix:
         target_flags:
-          - "sse"
           - "sse,sse2"
           - "sse,sse2,ssse3"
           - "sse,sse2,ssse3,sse4_1"
@@ -50,11 +49,10 @@ jobs:
           overwrite: true
           retention-days: 1
       - if: ${{ steps.generate.outputs.success == 'false' }}
-        uses: actions/github-script@v7
-        with:
-          script: |
-            echo "${{ steps.generate.outputs.msg }}"
-            core.setFailed("Generation for Intel x86 failed")
+        run: |
+          echo "Generation for Intel x86 failed"
+          echo "${{ steps.generate.outputs.msg }}"
+          exit 1
   package-for-intel:
     runs-on: ubuntu-latest
     name: Job to package TSL for Intel x86
@@ -107,11 +105,10 @@ jobs:
           overwrite: true
           retention-days: 1
       - if: ${{ steps.generate.outputs.success == 'false' }}
-        uses: actions/github-script@v7
-        with:
-          script: |
-            echo "${{ steps.generate.outputs.msg }}"
-            core.setFailed("Generation for ARM failed")
+        run: |
+          echo "Generation for ARM failed"
+          echo "${{ steps.generate.outputs.msg }}"
+          exit 1
   package-for-arm:
     runs-on: ubuntu-latest
     name: Job to package TSL for ARM
